import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const BASE = 'https://www.mytoolmate.top';

  const tools = [
    '/pdf-rotate',
    '/pdf-delete-pages',
    '/pdf-watermark',
    '/pdf-page-numbers',
    '/pdf-protect',
    '/pdf-unlock',
    '/pdf-flatten',
    '/pdf-crop',
    '/pdf-redact',
    '/image-to-pdf',
    '/txt-to-pdf',
    '/csv-to-pdf',
    '/pdf-viewer',
    '/pdf-to-image',
    '/pdf-organise',
    '/html-to-pdf',
    '/pdf-compress',
    '/pdf-sign',
    '/pdf-form',
    '/word-to-pdf',
    '/excel-to-pdf',
    '/pdf-ocr',
  '/about',
  '/contact',
  '/privacy-policy',
  '/terms',
  '/disclaimer',
  '/cookie-policy',
    '/age-calculator',
    '/ascii-art',
    '/audio-tester',
    '/av-converter',
    '/barcode-generator',
    '/base-converter',
    '/base64',
    '/case-converter',
    '/cert-decoder',
    '/citation-generator',
    '/code-unpacker',
    '/color-picker',
    '/compound-interest',
    '/coordinates',
    '/country-codes',
    '/cron-generator',
    '/csp-generator',
    '/css-tailwind',
    '/csv-to-json',
    '/curl-parser',
    '/data-visualizer',
    '/dead-pixel',
    '/dice-roller',
    '/diff-checker',
    '/dns-checker',
    '/emi-calculator',
    '/epoch-converter',
    '/exif-remover',
    '/favicon-generator',
    '/file-extension',
    '/gantt-chart',
    '/gradient-generator',
    '/graphql-beautifier',
    '/hash-generator',
    '/html-entity',
    '/http-status',
    '/image-converter',
    '/image-resizer',
    '/invoice-generator',
    '/ip-lookup',
    '/json-excel',
    '/json-formatter',
    '/jwt-debugger',
    '/keyboard-tester',
    '/lorem-ipsum',
    '/markdown-previewer',
    '/math-renderer',
    '/minifier',
    '/morse-code',
    '/password-entropy',
    '/password-generator',
    '/pdf-tools',
    '/percentage-calculator',
    '/qr-generator',
    '/random-picker',
    '/refresh-rate',
    '/regex-tester',
    '/salary-estimator',
    '/slug-generator',
    '/sql-formatter',
    '/stopwatch',
    '/subnet-calculator',
    '/svg-optimizer',
    '/svg-path-editor',
    '/text-stripper',
    '/time-card',
    '/timezone-converter',
    '/tts-player',
    '/unit-converter',
    '/url-encoder',
    '/user-agent',
    '/uuid-generator',
    '/venn-diagram',
    '/word-counter',
    '/xml-formatter',
    '/yaml-json',
  ];

  return [
    {
      url: BASE,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
    ...tools.map((href) => ({
      url: `${BASE}${href}`,
      lastModified: new Date(),
      changeFrequency: 'monthly' as const,
      priority: 0.8,
    })),
  ];
}
