export default function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
      <p className="text-sm text-muted-foreground mb-8">Last updated: September 2026</p>
      <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using MyToolMate at <span className="text-foreground font-medium">www.mytoolmate.top</span>, you agree to be bound by these Terms of Use. If you do not agree, please do not use the site.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">2. Use of Tools</h2>
          <ul className="list-disc list-inside space-y-2">
            <li>All tools are provided for lawful personal and professional use only.</li>
            <li>You must not use any tool to process, store, or transmit illegal content.</li>
            <li>You must not attempt to reverse-engineer, scrape, or automate access to the site in ways that degrade performance for other users.</li>
            <li>Tools that generate output (passwords, keys, codes) are provided as-is. You are responsible for validating output before using it in production systems.</li>
          </ul>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">3. Intellectual Property</h2>
          <p>The MyToolMate name, logo, and site design are the property of the site owner. Tool output generated by you (formatted JSON, converted images, etc.) belongs to you. You may not reproduce, redistribute, or commercially exploit the MyToolMate platform itself without written permission.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">4. No Warranty</h2>
          <p>MyToolMate is provided <strong className="text-foreground">"as is"</strong> without warranties of any kind, express or implied. We do not guarantee accuracy, completeness, or fitness for any particular purpose. Always verify tool output before relying on it for critical decisions.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">5. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, MyToolMate and its operators shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the site or its tools.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">6. External Links & APIs</h2>
          <p>Some tools connect to third-party APIs (e.g., IP geolocation services). We are not responsible for the availability, accuracy, or privacy practices of these third-party services.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">7. Modifications</h2>
          <p>We reserve the right to modify, suspend, or discontinue any tool or feature at any time without notice. We may also update these terms at any time; continued use constitutes acceptance.</p>
        </section>
        <section>
          <h2 className="text-base font-semibold text-foreground mb-2">8. Contact</h2>
          <p>Questions about these terms? Email us at <a href="mailto:logixmagix@proton.me" className="text-primary hover:underline">logixmagix@proton.me</a>.</p>
        </section>
      </div>
    </div>
  );
}
